# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-28 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20181128_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_list', '可以查看xadmin每张表里所有的数据'), ('crm_table_list_view', '可以访问xadmin表里每条数据的修改页'), ('crm_table_list_change', '可以对xadmin表里的每条数据进行修改'), ('crm_table_obj_add_view', '可以访问xadmin每张表的数据增加页'), ('crm_table_obj_add', '可以对xadmin每张表进行数据添加'))},
        ),
    ]
